version: "3.9"

networks:
    web-network:
        name: web-network
    traefik-network:
        external: true
        name: traefik-network

volumes:
    php-fpm-socket:

services:
    nginx:
        image: "nginx:1.25.2-alpine"
        restart: always
        working_dir: /app
        links:
            - php-fpm
        volumes:
            - ".:/app"
            - "./docker/nginx/nginx.conf:/etc/nginx/nginx.conf"
            - "./docker/nginx/sites-available:/etc/nginx/sites-available"
            - "./docker/nginx/sites-enabled:/etc/nginx/sites-enabled"
            - 'php-fpm-socket:/var/run/php-fpm.sock'
        networks:
            - web-network
            - traefik-network
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=traefik-network"
            # NGINX
            - "traefik.http.routers.nginx.rule=HostRegexp(`{domain:.+}`)"
            - "traefik.http.routers.nginx.priority=1"
            - "traefik.http.routers.nginx.service=nginx-svc"
            - "traefik.http.services.nginx-svc.loadbalancer.server.port=80"
            - "traefik.http.routers.nginx.entrypoints=websecure"
            - "traefik.http.routers.nginx.tls=true"
            - "traefik.http.routers.nginx.tls.certresolver=letsencrypt"
        depends_on:
            - php-fpm

    php-fpm:
        build: docker/php-fpm
        restart: always
        working_dir: /app
        links:
            - mariadb
        volumes:
            - ".:/app"
            - "./docker/php-fpm/php-overrides.ini:/usr/local/etc/php/conf.d/php-overrides.ini"
            - 'php-fpm-socket:/var/run/php/php8.3-fpm.sock'
        networks:
            - web-network

    adminer:
        image: adminer
        restart: always
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=traefik-network"
            # Adminer
            - "traefik.http.routers.adminer.rule=Host(`${ADMINER_HOSTNAME}`)"
            - "traefik.http.routers.adminer.service=adminer-svc"
            - "traefik.http.services.adminer-svc.loadbalancer.server.port=8080"
            - "traefik.http.routers.adminer.entrypoints=websecure"
            - "traefik.http.routers.adminer.tls=true"
            - "traefik.http.routers.adminer.tls.certresolver=letsencrypt"

    mariadb:
        image: "mariadb:11.1.2"
        restart: always
        working_dir: /app
        volumes:
            - ".:/app"
            - "./docker/mariadb/data:/var/lib/mysql"
            - "./docker/mariadb/logs:/var/log/mysql"
            - "./docker/mariadb/conf:/etc/mysql"
        networks:
            - web-network
        environment:
            MARIADB_ROOT_PASSWORD: "${MARIADB_ROOT_PASSWORD}"
        ports:
            - "3306:3306"
        healthcheck:
            test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MARIADB_ROOT_PASSWORD
            interval: 5s
            retries: 10

    redis:
        image: "redis:7.2.1-alpine"
        networks:
            - web-network
        environment:
            ALLOW_EMPTY_PASSWORD: "yes"
